baseURL = "https://nodragem.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Nodragem Makes:"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"
custom_css = ["style.css"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # DoIt theme version
  version = "0.2.X"
[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  gravatarEmail = ""
  # URL of avatar shown in home page
  avatarURL = "/img/profile.jpg"
  # URL the avatar links to
  avatarLinkURL = ""
[params.social]
  Bluesky = "@nodragem.bsky.social"
  Twitter = "@nodragem"

[menu]
  [[menu.main]]
    identifier = "games"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Games"
    url = "/games/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "illustrations"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Illustrations"
    url = "/illustrations/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "comics"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Comics"
    url = "/comics/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog-posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true

[params.doIt.lightGallery]
  download = false
  showMaximizeIcon = true